name: Build & Test (Maven)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-test:
    name: Build & Test on Windows
    runs-on: windows-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java (Temurin 21) with Maven cache
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Ensure Maven is installed
        shell: cmd
        run: |
          where mvn || choco install maven -y
          mvn -v

      - name: Build & Test
        shell: cmd
        run: mvn -B -ntp clean install

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: |
            **/target/surefire-reports/*
            **/target/failsafe-reports/*
          if-no-files-found: ignore
